# **Numpy: $n$-dimenziós adattömbök**
Fogarassyné Vathy Ágnes

## **1. Adattömbök létrehozása**

**Block 1.1** A *numpy* csomag importálása:

In [1]:
import numpy as np

**Block 1.2** **$n$-dimenziós adattömb** létrehozása:

In [2]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Block 1.3** **Üres adattömb** létrehozása (a memória inicializálása nélkül):

In [3]:
B = np.empty((2, 2))
print(B)

[[0. 0.]
 [0. 0.]]


**Block 1.4** **Nullmátrix** létrehozása:

In [4]:
C = np.zeros((2, 3))
print(C)

[[0. 0. 0.]
 [0. 0. 0.]]


**Block 1.5** **1-eseket tartalmazó mátrix** létrehozása:

In [5]:
D = np.ones((3, 2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


A fenti adatok *float64* típusúak. Ha integer típusú adatokkal szeretnénk feltölteni, akkor *dtype* paramétert is meg kell adnunk:

In [6]:
D = np.ones((3, 2), dtype=int)
print(D)

[[1 1]
 [1 1]
 [1 1]]


**Block 1.6** **Egységmátrix** lérehozása:

In [7]:
E = np.eye(3, dtype=int)
print(E)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Block 1.7** **Konstans értékekkel feltöltött mátrix** létrehozása:

In [8]:
F = np.full((2,3), 7)
print(F)

[[7 7 7]
 [7 7 7]]


**Block 1.8** **Adott lépésközzel** generált számokból álló mátrixot szintén könnyedén inicializálhatunk.  
Példaként hozzunk létre a [10,22) értéktartományból 2-es lépésközzel generált számokból egy 2$*$3-as adatmátrixot! Első lépésként hozzuk létre a számokat tartalmazó listát, majd a *resize* metódussal változtassuk meg a tömb méretét.

In [9]:
G = np.arange(10, 22, 2)
G.resize((2, 3))
print(G)

[[10 12 14]
 [16 18 20]]


**Block 1.9** **Egyenletes lépésközzel** generált számokból álló mátrix létrehozása.  
Példaként hozzunk létre a [0,10] értéktartományból generálva egy 1$*$5-ös tömböt oly módon, hogy az 5 szám egyenletesen legyen elosztva az értéktartományon belül!

In [10]:
H = np.linspace(0, 10, 5, endpoint=True, dtype=int)
print(H)

[ 0  2  5  7 10]


Ha a [0, 10) tartományban szeretnénk elosztani az 5 számot, akkor ezt a következőképpen tudjuk megtenni: 

In [11]:
H = np.linspace(0, 9, 5, endpoint=False)
print(H)

[0.  1.8 3.6 5.4 7.2]


**Block 1.10** **Random számokból** álló adattömb létrehozására számos lehetőség létezik.  
Ehhez érdemes áttekinteni a következő leírást: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html.  

Csupán néhány példa:  
- 2$*$3-as adattömb [0, 1) intervallumból egyenletes eloszlással:

In [12]:
I = np.random.rand(2, 3)
print(I)

[[0.61688498 0.13103781 0.96775356]
 [0.64902057 0.99453202 0.61841349]]


- 2∗3-as adattömb [0, 1) intervallumból normál eloszlással:

In [13]:
I = np.random.randn(2, 3)
print(I)

[[-0.43095206 -0.76006434  1.29292415]
 [ 0.57974862  0.69921686  0.6748429 ]]


- [100, 200) intervallumból generált 10 db egész szám egyenletes eloszlással:

In [14]:
J = np.random.randint(100, 200, 10)
print(J)

[125 179 160 147 159 183 145 122 129 185]


- [10, 20) intervallumból generált 5 db véletlen szám egyenletes eloszlással:

In [15]:
K = np.random.uniform(10, 20, 5)
print(K)

[14.96996142 16.81327189 17.84542614 17.3838223  15.26916344]


- [10, 20) intervallumból generált 2*3-as adattömb random, egyenletes eloszlással:

In [16]:
L = np.random.uniform(10, 20, (2, 3))
print(L)

[[15.38842316 18.13457065 16.72472265]
 [12.41796377 11.41855424 17.79471286]]


<br>

## **2. Tömbök építése**

Hozzunk létre 2 adattömböt, majd "másoljuk" egymás mellé őket a lehetséges 2 módon!

In [17]:
T1 = np.array([[1, 2, 3], [4, 5, 6]])
print(T1)

[[1 2 3]
 [4 5 6]]


In [18]:
T2 = np.array([[7, 8, 9], [10, 11, 12]])
print(T2)

[[ 7  8  9]
 [10 11 12]]


**Block 2.1** T1 és T2 **tömbök halmozása vertikálisan**:

In [19]:
np.concatenate((T1, T2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Ugyanezen felafat megoldása másképp:

In [20]:
np.vstack((T1, T2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Block 2.2** T1 és T2 **tömbök halmozása horizontálisan**:

In [21]:
np.concatenate((T1, T2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Ugyanezen feladat megoldása másképp:

In [22]:
np.hstack((T1, T2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

<br>

## **3. Tömbök mérete és típusa**

Gyakran van szükségünk arra, hogy lekérdezzük meglévő adattömbjeink méretét, és a bennük található adatok típusát. Ezt a következőképpen tudjuk megtenni: 

**Block 3.1** **Tömb dimenzióinak száma**:

In [23]:
T1.ndim

2

**Block 3.2** **Tömb méretének** lekérdezése:

In [24]:
T1.shape

(2, 3)

**Block 3.3** **Tömb elemeinek száma**:

In [25]:
T1.size

6

**Block 3.4** **Tömb 'hossza'** (benne lévő listák száma):

In [26]:
len(T1)

2

**Block 3.5** Tömbben lévő **elemek típusa**:

In [27]:
T1.dtype.name

'int64'

**Block 3.6** Tömb elemeinek **típuskonverziója**:

In [28]:
print(T1)
T1.dtype.name

[[1 2 3]
 [4 5 6]]


'int64'

In [29]:
M = T1.astype(float)
print(M)
M.dtype.name

[[1. 2. 3.]
 [4. 5. 6.]]


'float64'

<br>


## **4. Tömbök elemei és résztömbök (slice and dice)**

Tömb elemeinek elérésekor ügyelnünk kell arra, hogy:
- a sor- és oszlopindexek 0-tól kezdődnek 
- tartományok megadása esetén alulról zárt, felülről nyitott tartományokat tudunk megadni

Hivatkozások:
- [sor, oszlop]  
- : minden sor/oszlop
- :n az első $n$ sor/oszlop
- :-n kivéve az utolsó $n$ sor/oszlop
- ::n minden $n$-edik sor/oszlop
- ::-1 sorok/oszlopok inverze



Tekintsük az *A* tömböt, majd próbáljuk ki a fenti lehetőségek különféle kombinációit!

In [30]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Block 4.1**  A 2. sor 4. oszlopának eleme:

In [31]:
print(A[1, 3])

8


**Block 4.2** A 3. oszlop elemei:

In [32]:
print(A[:, 2])

[ 3  7 11 15]


**Block 4.3**  A 4. sor elemei:

In [33]:
print(A[3, :])

[13 14 15 16]


**Block 4.4** A 2. és 3. sor 2. oszlopában lévő elemek:

In [34]:
print(A[1:3, 1])

[ 6 10]


**Block 4.5** Az 1. és a 3. oszlop elemei:

In [35]:
print(A[:, [0, 2]])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


**Block 4.6** Az első két oszlop elemei:

In [36]:
print(A[:, :2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


**Block 4.7** A teljes adattömb, kivéve az utolsó oszlop:

In [37]:
print(A[:, :-1])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


**Block 4.8** Minden 2. sor és oszlop elemei (az 1. sor és 1. oszlop benne van):

In [38]:
print(A[::2, ::2])

[[ 1  3]
 [ 9 11]]


**Block 4.9** A tömb fordított oszlopsorrendben:

In [39]:
print(A[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


<br>


## **5. Keresés a tömbökben**

Hozzunk létre egy tömböt, melyben majd érték szerint fogunk keresni!

In [40]:
x = np.array([[5, 9, 2], [3, 0, 4]])
print(x)

[[5 9 2]
 [3 0 4]]


Az adattömbök elemei között legegyszerűbben logikai feltételek megadásával kereshetünk. Eredményképpen azokat az elemeket kapjuk vissza, melyek kielégítik a logikai feltételt.  
<br>
**Block 5.1** Melyek az *x* tömb azon elemei, amelyek értéke kisebb, mint 5?

In [41]:
x[x < 5]

array([2, 3, 0, 4])

**Block 5.2** Melyek az *x* tömb páros elemei?

In [42]:
x[x % 2 == 0]

array([2, 0, 4])

**Block 5.3** Ha azt szeretnénk megtudni, hogy mik azon elemek **indexei**, amelyek eleget tesznek a feltételnek, akkor az *np.argwhere* függvényt kell alkalmaznunk. (Használható még az *np.where* is.)

In [43]:
np.argwhere(x < 5)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [44]:
np.where(x < 5)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

**Block 5.4** Gyakran van szükségünk a **nem 0 elemek keresésére** is, melyet így is meg tudunk tenni:

In [45]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 2]])

<br>

## **6. Hivatkozás és másolás**

**Block 6.1** Nem mindegy, hogy egy adattömbre hivatkozunk-e egy másik névvel, vagy másolatot hozunk belőle létre. Előbbi esetben **referenciaként** jön létre az adattömb, míg a második esetben az eredeti adattömb **másolata** készül el.  
<br>
Nézzünk rá egy rövid példát!

In [46]:
x = np.array([[5, 9, 2], [3, 0, 4]])
y = x  # reference
z = np.copy(x)  # copy
x

array([[5, 9, 2],
       [3, 0, 4]])

In [47]:
x[0, 0] = 999

In [48]:
print(x)

[[999   9   2]
 [  3   0   4]]


In [49]:
print(y)

[[999   9   2]
 [  3   0   4]]


In [50]:
print(z)

[[5 9 2]
 [3 0 4]]


<br>

## **7. Egyéb**

**Block 7.1** **Tömbök transzponálása**:

In [51]:
np.transpose(A)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])